### ISSUE TITLE
Updated RNUI

### ISSUE THREAD

**Issue by Michael21107** [yoep/AutomaticRoadblock#168]
I noticed u updated the bundled RNUI, I think u should release it (also on lcpdfr.com) so people who installed the newest version won't have to (if they want/need it) download the newest rnui manually

**Comment by yoep** [comment]
Duplicate of #163

**Comment by Michael21107** [comment]
i know that u already fixed it, just that it would be nice to release it as well

**Comment by yoep** [comment]
A new release will be on it's way once I found the time to test the latest changes :)

**Comment by Michael21107** [comment]
gotcha, good luck :)
