### ISSUE TITLE
lml question

### ISSUE THREAD

**Issue by Michael21107** [yoep/AutomaticRoadblock#169]
how does the install.xml know where to put the files or what files to install if the resource folder is where?

**Comment by yoep** [comment]
LML uses the installation directory of GTA V to determine where the files need to be installed.
It then uses the "resource folders" to place the files included in the defined directory into the installation directory of GTA V.
This means it that the structure of `GameFolder` should follow the structure of the GTA V installation directory.

**Comment by Michael21107** [comment]
gotcha, btw does the resource folder have to be in the same folder as the install.xml?

**Comment by yoep** [comment]
The `install.xml` must always be in the root directory of the zip file.
The resource folder itself defined under `GameFolder` doesn't need to be in the same location as the `install.xml`, so it can be a subdirectory within the zip file.

**Comment by Michael21107** [comment]
what if there are more folders matching the resource folder?

**Comment by yoep** [comment]
As mentioned in the LML docs, the `GameFolder` definition is always specific and not a matching pattern (unless the behavior changed in newer versions).
This means that the `GameFolder` cannot match multiple folders as it a simple "file system copy" command.

**Comment by Michael21107** [comment]
I mean the folder that contains things to install

**Comment by yoep** [comment]
You've kinda lost me now.
Could you elaborate a little bit about what you mean?

**Comment by Michael21107** [comment]
@yoep

**Comment by yoep** [comment]
I think it copies everything from` folder1` and `folder2` and probably overwrites items from `folder1` with `folder2` items if it encounters duplicates.
But I'm not certain, so you should check the LML docs for it to be sure.

**Comment by Michael21107** [comment]
gotcha, thanks
