### ISSUE TITLE
Wrong officer outfits

### ISSUE THREAD

**Issue by Michael21107** [yoep/AutomaticRoadblock#177]
![image](https://github.com/yoep/AutomaticRoadblock/assets/121039033/0b47a6a9-89f2-4ebe-87fc-4b3e19d5cd42)

**Comment by yoep** [comment]
Hi

Officers, including their outfits, are spawned and managed by LSPDFR.
So I cannot fix this issue for you unfortunately as this is not directly defined by the plugin, only the unit type that is spawned.

**Comment by Michael21107** [comment]
As this is not something you fixed, shouldn't the issue be closed as not planned?
